language: go

go:
  - 1.6

install:
  - make install-glide
  - export PATH="$HOME/bin:$PATH"
  - make setup

env:
  - GOOS=linux GOARCH=amd64
  - GOOS=darwin GOARCH=amd64

script:
  - make test
  - make build
